### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#102]
Before release the 1.2 version I suggest to improve the readme :

- add 'normal' module installation (+ command line (wget ...))
- Describe each command and add examples
- move the 'create you own command' part in a dedicated `developpers.md` file.

I can do it.

WDYT ? ( @jf-viguier @nenes25 )

**Comment by nenes25** [comment]
Sure it will be a good thing.
To generate a basic documentation for the commands it's really easy as symfony console do it alone :)
Simply do 
`php bin/console list fop --format=md > COMMANDS.md`
In my other project this doc is automatically generated on each push

**Comment by SebSept** [comment]
Can you give us a link to see it ?

**Comment by nenes25** [comment]
you can see it here : https://gist.github.com/nenes25/a324be4da7e61b73ae402b7becc9bc48

**Comment by SebSept** [comment]
Great. I didn't know help can rendered as markdown.
We can put it inside readme or generate it after commit on a separated file ...

**Comment by nenes25** [comment]
Yes i thinks a separate file "COMMANDS.md" file should do the job
Do you want me do do a pull request for this ? (only for the current file now )

**Comment by SebSept** [comment]
Why not.
The generation will be triggered on commit ? Using Grumphp ?

**Comment by nenes25** [comment]
Maybe with grumpPhp i'll check
Currently i just have a pre-commit hook

**Comment by SebSept** [comment]
Don't spend too much time on it.
I don't know if it's even possible with this old version of grumphp.
It's ok if only a few of us can register the precommit hook :)

**Comment by SebSept** [comment]
Maybe, it's possible to create a php script in `dev/.devtools` that will trigger the COMMANDS.md generation.
So the script is in the repo, ready to use.
And/Or add a composer script. 
I don't know.
Maybe the composer option is the easiest, but it's a bit hidden...

If you plan to release this @nenes25 , assign yourself to the task.
