### ISSUE TITLE
Protect module folder

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#104]
Add an .htaccess to avoid acces from browser.
I think it's possible to protect the whole module folder. No ?

**Comment by nenes25** [comment]
I think a file with this content should works ( it's the same that protect the bin directory )

`# Apache 2.2
<IfModule !mod_authz_core.c>
    Order deny,allow
    Deny from all
</IfModule>

# Apache 2.4
<IfModule mod_authz_core.c>
    Require all denied
</IfModule>
`

**Comment by SebSept** [comment]
Sure.
Do you see any reason not to protect the folder ?
I means, is there any module that need a web access ?
Maybe we can protect and see if someones has a problem...
