### ISSUE TITLE
composer platform

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#118]
define target php version using  composer platform config.
https://getcomposer.org/doc/06-config.md#platform
can be useful when using a  more recent php version while developing this fop_console.

Not a good idea ?

**Comment by Kaudaj** [comment]
Indeed, it doesn't look like a good practice...
https://github.com/composer/composer/issues/5163#issuecomment-207347350

I wonder if using the `--ignore-platform-reqs` option for dev dependencies only is problematic? They will never be used in production environment but on the other hand, not sure if mentioning that developers have to use the PHP 7.3 in the documentation will be enough for DX...

**Comment by SebSept** [comment]
I think using plateform requirement is a good think to ensure annonced compatibility.

**Comment by SebSept** [comment]
but ready the doc again, I'm not sure it's a good thing.
If no ones has the knowledge, we should close this issue..
@friends-of-presta/fop-console-contributors

**Comment by Kaudaj** [comment]
Yup it doesn't seem to be a solution for this use case.

**Comment by SebSept** [comment]
if it's finally a good thing, you can reopen or comment this.
