### ISSUE TITLE
php 7.4 must be supported

### ISSUE THREAD

**Issue by theyough** [friends-of-presta/fop_console#119]
**Is your feature request related to a problem? Please describe.**
When i'm using docker-compose with prestashop 1.7.8, the php version is 7.4

**Describe the solution you'd like**
Will be nice to support the new prestashop 1.7.8 with php 7.4 min

**Comment by okom3pom** [comment]
@theyough 

Can you say us the command who don't work with php 7.4 ? 

I try a lot or command and i don't find one ?

![Capture d’écran de 2021-06-23 15-38-42](https://user-images.githubusercontent.com/5064590/123106768-373e8280-d439-11eb-8f8d-6bb7d3130d6f.png)

PS : Sorry for answer time

**Comment by SebSept** [comment]
I just installed Prestashop 1.7.8.0 beta 1.
And fop_console 1.3.3
With php 7.4.20
Not on docker but I guess that doesn't change anything.

The command I tested are also ok.

Can you please tell us what is exactly the problem @theyough ?

**Comment by SebSept** [comment]
maybe @theyough said that on the readme.md php 7.4 is not marked as supported...
Can you please take 15 seconds to provide feedback @theyough ?

**Comment by theyough** [comment]
Sorry guys, I don't have to test it again.
You can close the issue

**Comment by okom3pom** [comment]
Thank you for feedback @theyough i add the php 7.4 on the readme
