### ISSUE TITLE
Add a command to reset a theme

### ISSUE THREAD

**Issue by jf-viguier** [friends-of-presta/fop_console#120]
Reset command can be useful :
- there is no such command in ps command line
- BO Reset button is available in debug mode only

**Comment by SebSept** [comment]
It looks like this command is implemented @jf-viguier. ( `fop:theme-reset` on dev branch )
right ?

**Comment by jf-viguier** [comment]
Yes

**Comment by SebSept** [comment]
Issue closed.
Feature implemented
