### ISSUE TITLE
start using phpstan really

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#127]
currently phpstan is at level 0.
that's useless.
I suggest to start at level 4, that pretty simple to fix, and a simple (weak) base.

At the moment I introduced phpstan, I configured it at level 0 to avoid annoyance with existing problem.
I was unaware of the --baseline option (I did not found what it was for).
The baseline make us able to run phpstan at any level and ignore existing issues detected.
So we can start using it at any level without having to fix all existing errors.

So all new PR will have to pass at the level.

I suggest 4 for a first start...

**Comment by okom3pom** [comment]
level : 5️⃣  passe pour moi , donc 4️⃣  oui c'est un début !
