### ISSUE TITLE
incompatible path on baseline for phpstan (alone) and grumphp.

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#150]
**Describe the bug**
`composer fop_check` (grumphp) and `vendor/bin/phpstan` handle the .devtools/phpstan_baseline.neon with different path root.

So if an error on phpstan_baseline.neon is reported with a correct path for phpstan standalone, it's ok for grumphp.
The opposite it also true.

```neon
parameters:
	ignoreErrors:
		-
			message: "#^Call to an undefined method Symfony\\\\Component\\\\Console\\\\Application\\:\\:getKernel\\(\\)\\.$#"
			count: 1
			path: src/Commands/CheckServiceContainer.php

# That's fine, dump() can handle multiple values - This is not an error. https://github.com/symfony/var-dumper/blob/3.4/Resources/functions/dump.php
		-
			message: "#^Function dump invoked with 2 parameters, 1 required\\.$#"
			count: 1
			path: ../src/Commands/Configuration/Export.php
```

with this baseline, first path is ok for grumphp, not phpstan directly.
second path it not ok for grumphp but ok for phpstan.

Maybe we could move the baseline file at the root.

No one reported this recent problem.
Do you use grumphp on pre-commit hook (or `composer fop_check`) ? @okom3pom @Kaudaj ?

**Comment by okom3pom** [comment]
I use grumphp on pre-commit hook never composer fop check

But when i test your PR : https://github.com/friends-of-presta/fop_console/pull/149 i reproduce .

**Comment by SebSept** [comment]
What's the content of your precommit hook ?
It fails on my machine.

**Comment by okom3pom** [comment]
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/2: phpcsfixer... 
Running task 2/2: phpstan... 
Running task 1/2: phpcsfixer... ✘
Running task 2/2: phpstan... 
Running task 1/2: phpcsfixer... ✘
Running task 2/2: phpstan... ✘
             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
       ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄███▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄███████                       ██████████
     ███████▀  ▀▀▀▀▀▄      ▄▀▀▀▀▀     █████ ▀
      ▐████      ▐██        ▐██        ████▌
      ████▌                            ███
       ▌██▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀███████████▀     ▀▀███████████
          ██████████▄███████▄███████████
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ██▌
                        ██▀   ▐▀

       ██████████████████████████████████
       █░░░░░░▀█▀░░░░░░▀█░░░░░░▀█▀░░░░░▀█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░░░░░▄█░░▄▄▄▄▄█
       █░░▐█▌░░█░░░██░░░█░░░░████░░░░░░░█
       █░░░█░░░█▄░░░░░░▄█░░░░████▄░░░░░▄█
       ██████████████████████████████████


phpcsfixer
==========

1) fop_console.php (no_trailing_whitespace_in_comment)

You can fix all errors by running following commands:
'/var/www/html/178/PrestaShop/modules/fop_console/vendor/bin/php-cs-fixer' '--config=.php_cs.dist' '--path-mode=intersection' '--verbose' 'fix' 'fop_console.php'

phpstan
=======

Phpstan configuration problem : 

     You must configure the path to Prestashop in "/var/www/html/178/PrestaShop/modules/fop_console/.devtools/.phpstan_bootstrap_config.php
     You left the default value.

Note: Using configuration file /var/www/html/178/PrestaShop/modules/fop_console/phpstan.neon.dist.
To skip commit checks, add -n or --no-verify flag to commit command

 I can fix some stuff automatically, do you want me to? (yes/no) [yes]:
 > Auto-Fixing tasks...
Running fixer 1/1: phpcsfixer... ✔

 [WARNING] Please review the code changes that I made!

**Comment by okom3pom** [comment]
**With composer fop_check**

okom3pom@okom3pom-N501VW:~/www/178/PrestaShop/modules/fop_console$ composer fop_check
> grumphp run --ansi
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/2: phpcsfixer... ✔
Running task 2/2: phpstan... ✘

             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
       ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄███▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄███████                       ██████████
     ███████▀  ▀▀▀▀▀▄      ▄▀▀▀▀▀     █████ ▀
      ▐████      ▐██        ▐██        ████▌
      ████▌                            ███
       ▌██▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀███████████▀     ▀▀███████████
          ██████████▄███████▄███████████
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ██▌
                        ██▀   ▐▀

       ██████████████████████████████████
       █░░░░░░▀█▀░░░░░░▀█░░░░░░▀█▀░░░░░▀█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░░░░░▄█░░▄▄▄▄▄█
       █░░▐█▌░░█░░░██░░░█░░░░████░░░░░░░█
       █░░░█░░░█▄░░░░░░▄█░░░░████▄░░░░░▄█
       ██████████████████████████████████

phpstan
=======

Phpstan configuration : _PS_ROOT_DIR_ successfully set to /home/okom3pom/www/178/PrestaShop/
Warning: Use of undefined constant _THEME_NAME_ - assumed '_THEME_NAME_' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 29

Warning: Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 30

Warning: Use of undefined constant _THEME_NAME_ - assumed '_THEME_NAME_' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 30

Warning: Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 39

Warning: Use of undefined constant _THEME_NAME_ - assumed '_THEME_NAME_' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 40

Warning: Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 46

Warning: Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 63

Warning: Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 64

Warning: Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 65

Warning: Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 66

Warning: Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 67
Detected PS version 1.7.8.0
 ------ ----------------------------------------------------------------------- 
  Line   src/Commands/CheckServiceContainer.php                                 
 ------ ----------------------------------------------------------------------- 
         Ignored error pattern #^Call to an undefined method                    
         Symfony\\Component\\Console\\Application\:\:getKernel\(\)\.$# in path  
         /var/www/html/178/PrestaShop/modules/fop_console/src/Commands/CheckSe  
         rviceContainer.php was not matched in reported errors.                 
 ------ ----------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------- 
  Line   src/Commands/Configuration/Export.php                                  
 ------ ----------------------------------------------------------------------- 
         Ignored error pattern #^Function dump invoked with 2 parameters, 1     
         required\.$# in path                                                   
         /var/www/html/178/PrestaShop/modules/fop_console/src/Commands/Configu  
         ration/Export.php was not matched in reported errors.                  
 ------ ----------------------------------------------------------------------- 

 [ERROR] Found 2 errors                                                         


Note: Using configuration file /var/www/html/178/PrestaShop/modules/fop_console/phpstan.neon.dist.
PHP Warning:  Use of undefined constant _THEME_NAME_ - assumed '_THEME_NAME_' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 29
PHP Warning:  Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 30
PHP Warning:  Use of undefined constant _THEME_NAME_ - assumed '_THEME_NAME_' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 30
PHP Warning:  Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 39
PHP Warning:  Use of undefined constant _THEME_NAME_ - assumed '_THEME_NAME_' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 40
PHP Warning:  Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 46
PHP Warning:  Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 63
PHP Warning:  Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 64
PHP Warning:  Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 65
PHP Warning:  Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 66
PHP Warning:  Use of undefined constant __PS_BASE_URI__ - assumed '__PS_BASE_URI__' (this will throw an Error in a future version of PHP) in /var/www/html/178/PrestaShop/config/defines_uri.inc.php on line 67
To skip commit checks, add -n or --no-verify flag to commit command
Script grumphp run --ansi handling the fop_check event returned with error code 1

**Comment by okom3pom** [comment]
Je me demande si j'ai bien compris le problème avec mon Anglais  ?

**Comment by SebSept** [comment]
Merci. Je regarde ça Lundi.
Mais on dirait que tu as le même problème que moi

**Comment by Kaudaj** [comment]
### `composer fop_check` on `dev` branch :

> grumphp run --ansi
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/2: phpcsfixer... ✔
Running task 2/2: phpstan... ✘
             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
       ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄███▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄███████                       ██████████
     ███████▀  ▀▀▀▀▀▄      ▄▀▀▀▀▀     █████ ▀
      ▐████      ▐██        ▐██        ████▌
      ████▌                            ███
       ▌██▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀███████████▀     ▀▀███████████
          ██████████▄███████▄███████████
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ██▌
                        ██▀   ▐▀

       ██████████████████████████████████
       █░░░░░░▀█▀░░░░░░▀█░░░░░░▀█▀░░░░░▀█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░░░░░▄█░░▄▄▄▄▄█
       █░░▐█▌░░█░░░██░░░█░░░░████░░░░░░░█
       █░░░█░░░█▄░░░░░░▄█░░░░████▄░░░░░▄█
       ██████████████████████████████████


phpstan
=======

Phpstan configuration : _PS_ROOT_DIR_ successfully set to /var/www/prestashop-sandboxDetected PS version 1.7.8.0
 ------ -----------------------------------------------------------------------
  Line   src/Commands/CheckServiceContainer.php
 ------ -----------------------------------------------------------------------
         Ignored error pattern #^Call to an undefined method
         Symfony\\Component\\Console\\Application\:\:getKernel\(\)\.$# in path
         /var/www/prestashop-sandbox/modules/fop_console/src/Commands/CheckSer
         viceContainer.php was not matched in reported errors.
 ------ -----------------------------------------------------------------------

 ------ -----------------------------------------------------------------------
  Line   src/Commands/Configuration/Export.php
 ------ -----------------------------------------------------------------------
         Ignored error pattern #^Function dump invoked with 2 parameters, 1
         required\.$# in path
         /var/www/prestashop-sandbox/modules/fop_console/src/Commands/Configur
         ation/Export.php was not matched in reported errors.
 ------ -----------------------------------------------------------------------

 [ERROR] Found 2 errors


Note: Using configuration file /var/www/prestashop-sandbox/modules/fop_console/phpstan.neon.dist.
To skip commit checks, add -n or --no-verify flag to commit command
Script grumphp run --ansi handling the fop_check event returned with error code 1

### Pre-commit hook :

Running `git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -` gives me this :

hint: The '.git/hooks/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
(reading log message from standard input)

Is it the right way to test pre-commit hook? If not, could you give me the right way to do it?

**Comment by SebSept** [comment]
ok.
So grumphp has errors, but you can commit since your pre-hook file is not executable, @Kaudaj 
Maybe the same for @okom3pom .

Maybe we should remove it and add note for developpers about php-cs-fixer / phpstan / pre-commit hook..
WDYT ?

**Comment by Kaudaj** [comment]
I'm not familiar with grumphp at all, so I don't think that my opinion will be useful...
I just run phpstan and php-cs-fixer locally before committing (or after if I forgot).

**Comment by SebSept** [comment]
Ok, thanks for feedback.

**Comment by Kaudaj** [comment]
First method should be great imo, but we could do it without phive at first, should be easier?

**Comment by SebSept** [comment]
right, no need to use phive ;) 
Important is the installing part of the precommit hook and the fact the precommit hook script is, in fact, a composer script (easy to find and change) .

(The downside is that it may not work on ™️ Microsoft Windows )

**Comment by Kaudaj** [comment]
In php : https://stackoverflow.com/questions/38895739/composer-script-section-os-dependent ?
Otherwise, I don't know...

**Comment by Kaudaj** [comment]
Upgrading GrumPHP seems to fix the issue, but it's not a solution if we support PHP 7.2.
I tried to move everything in .devtools but didn't manage to make it work like this (same issue).
So I suggest either to stop PHP 7.2 support (can we do it for development only?) or to move phpstan_baseline.neon at the root.

**Comment by okom3pom** [comment]
I don't use php 7.2 anymore

**Comment by SebSept** [comment]
I have sites running on php 7.2.
Changing compatibility is a big issue, should not be taken so fast.
Letting development tools define the project properties is an horrible thing to me ! (that's why phive was created by the way).

It's possible to write code with php 7.2 as target but use php with higher version for development, I suppose, that's the intent of `plateform` option of composer ... -> #118

**Comment by Kaudaj** [comment]
Ah great news, let's update GrumPHP and use this plateform option then!
Otherwise, I totally agree with you.

**Comment by SebSept** [comment]
> Indeed, it doesn't look like a good practice...
composer/composer#5163 (comment)

> I wonder if using the --ignore-platform-reqs option for dev dependencies only is problematic? They will never be used in production environment but on the other hand, not sure if mentioning that developers have to use the PHP 7.3 in the documentation will be enough for DX...

**Comment by SebSept** [comment]
interesting and hot conversation !! 
Another problem mentioned in the thread is that it's a bad idea to develop with versions of packages that are not the one that will be shipped.
So it means, that the dependencies should be upgraded just before running grumphp each time, that's non-sens.

One option could be to --ignore-platefom-reqs for just one package (grumph), but that's not possible.

So there's no way to use grumphp with our current requirements. Is this correct ?

**Comment by Kaudaj** [comment]
Yep, unless we move phpstan_baseline.neon but personnally, I hate having everything at the root.
I will try to replace grumphp with composer scripts.

**Comment by SebSept** [comment]
finally, will someone try to move  phpstan_baseline.neon at the root of the repo ?

**Comment by Kaudaj** [comment]
I already tried and it works. The question is whether we want it at the root or not.

**Comment by SebSept** [comment]
I also tried without success.
If we can get it working, that's the better solution otherwise, we'll remove it.
Can you make a PR ?
