### ISSUE TITLE
Guzzle json method is deprecated

### ISSUE THREAD

**Issue by okom3pom** [friends-of-presta/fop_console#176]
#### Describe the bug
Guzzle json method is deprecated for PSR-7, we can use 

```
            $content = json_decode($response->getBody()->getContents());
            $version = $content->tag_name;
```

### Fop Console Version
Fop console version 1.4.0

### Prestashop Version
8.0

### Php Version
Your server php version (7.4+)

### Additional context

![Capture d’écran de 2021-10-13 08-29-13](https://user-images.githubusercontent.com/5064590/137079202-a355a4de-6f62-4482-a8b7-46c66a589a93.png)

**Comment by SebSept** [comment]
ok, I'll fix it asap

**Comment by SebSept** [comment]
are we supposed to support PrestaShop 8 ?

**Comment by okom3pom** [comment]
Not at the moment.
It's better to note and correct when you see a problem.
