### ISSUE TITLE
upgrade prestashop/dev-tools

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#199]
upgrade to a recent version of prestashop/dev-tools.

Notice the need to rename the php-cs configuration file : ``.php_cs.dist`` file to ``.php-cs-fixer.dist.php``

**Comment by okom3pom** [comment]
https://github.com/PrestaShop/php-dev-tools/releases/tag/v4.2.0

**Comment by okom3pom** [comment]
New one https://github.com/PrestaShop/php-dev-tools/releases/tag/v4.2.1

**Comment by SebSept** [comment]
done in #223
