### ISSUE TITLE
Add a command to override a file

### ISSUE THREAD

**Issue by jf-viguier** [friends-of-presta/fop_console#20]
Could be fop:override filepath
The overrided path can be :
- A tpl/css/js of a theme in his child theme
- A legacy class/controller in override folder
- A module main file

**Comment by SebSept** [comment]
Would be great to have this command :+1:

**Comment by okom3pom** [comment]
In the same idea I wanted to add a command to disable or enable all overrides.

Like here :

https://github.com/nenes25/prestashop_console/pull/3/files

To go deep I also wanted to add the possibility to desactive or active a specific override by playing on the class_index.php and file extension in the override folder.

I don't know if it's the best way

Sorry for my english.

**Comment by jf-viguier** [comment]
Merci @okom3pom bonne idée, est-ce que tu peux ouvrir une issue dédiée stp ?

**Comment by okom3pom** [comment]
Oui, je ne voulais pas ajouter d'issue ayant trouvé une qui parlait des overrrides, je fais ça.

**Comment by jf-viguier** [comment]
On essaie de faire une issue par commande. Ce serait une commande du genre fop:override-status enable/disable

**Comment by SebSept** [comment]
Started : #46 

Because pr is started, I'm not sure this issue is still relevant... (?).

**Comment by jf-viguier** [comment]
Merci @SebSept pour démarrer cette commande qui est importante.
J'y ai déjà un peu réfléchi, on peut en discuter sur le slack si besoin.
Pour l'issue on part sur le même principe que presta : on cloture l'issue quand la pr est mergée.

**Comment by SebSept** [comment]
ok pour l'issue.
Je vais y aller doucement pour le dev...

**Comment by SebSept** [comment]
Finalement, j'ai supprimé la pull request.
Mon travail est ici : https://github.com/SebSept/fop_console/tree/command_override2

Le problème c'est que la branche dev a évolué entre le moment ou j'ai créé la pull request et le moment ou je pousse dedans.
Rebaser ma branche locale de travail ne fait que rajouter des commits qui n'ont rien a voir dans le pull request, faudrait rebaser le pull request, ou ? .. enfin bref. Si vous savez il faut s'y prendre, je suis preneur de l'info sinon je chercherai ...
