### ISSUE TITLE
Prefer "stable" in composer.json generated by fop:module:generate

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#248]
https://github.com/friends-of-presta/fop_console/blob/b348416252436d84c2868f35e45ab55f12443034/src/Resources/templates/generate_module_command/module/composer.json.twig#L13

I think that `stable` should be the default. This is the default for composer.
There must be a strong reason not to provide a file with this value.

WYT @luigimassa ?

https://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by luigimassa** [comment]
hello
resolved in new pull request

**Comment by SebSept** [comment]
done https://github.com/friends-of-presta/fop_console/commit/097b83719e23a30aca4b7b5c8ddd9221fda1b312
