### ISSUE TITLE
travis-ci build fails on pull request

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#25]
build fail example : https://github.com/friends-of-presta/fop_console/pull/24/checks?check_run_id=406733766

I suppose it's because of php-cs-fixer version.

- ci depends on `prestashop/php-dev-tools` ( https://github.com/friends-of-presta/fop_console/blob/master/composer.json#L25 )
- `prestashop/php-dev-tools` depends on "friendsofphp/php-cs-fixer": "^2.14" (https://github.com/PrestaShop/php-dev-tools/blob/master/composer.json#L8)

I pretty sure (but not definitively) that the latest version of php-cs-fixer is ok to solve this problem.

Travis-ci may use the latest or 2.16 version, not the version in the `prestashop/php-dev-tools`, unless `prestashop/php-dev-tools` gets updated...

**Comment by SebSept** [comment]
What about getting rid of prestashop/php-dev-tools ?
It does not provide anything important or that could easily be replaced.
we could manage php-cs-fixer version (then have builds passing).

**Comment by zalexki** [comment]
fixed by #27

**Comment by SebSept** [comment]
:+1:
