### ISSUE TITLE
Define Copyright header

### ISSUE THREAD

**Issue by nenes25** [friends-of-presta/fop_console#4]
We must defines a consistent copyright headers for each files of the project.
Following the example of Prestashop's one i'll suggest this  : 

`
/**
 * 2019-present Friends of Presta community
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @author    Friends of Presta community
 * @copyright 2019-present Friends of Presta community
 * @license   https://opensource.org/licenses/MIT MIT
 */
`

WDYT ?

**Comment by jf-viguier** [comment]
@friends-of-presta/core-friends what do you think ?
It's seems good to me
