### ISSUE TITLE
Add a command to list registred hooks of a module.

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#83]
A command that lists all the hook a module is attached on.

example : `./bin/console fop:module:hooks [module_name]` (may not be a good command choice)
Outputs : 
``` module [module_name] is hooked on : 
- displayHeader
- actionBlabla
- ...
```

Even better (v2 ?) 
list the possible hooks (module implements hookDisplayXXX) and the currently used hooks.
So we can imagine a table like that : 
```
Module [module_name] hooks : 
-------------------------------------
| hook                 |  hooked   |
-------------------------------------
| displayHeader        | yes       |
| actionBlaBla         | no        |
-------------------------------------
```

**Comment by SebSept** [comment]
You want to implement it ?
Go on (notify us to avoid working on an already opened work)

**Comment by nenes25** [comment]
@SebSept i've already implement this functionality on prestashopConsole.
I can make a back-port :) ( V1 only for now )

**Comment by SebSept** [comment]
Yeah, and it works fine (just tested now) it could be nice if you can spend some time on it 👍🏼
