### ISSUE TITLE
Rearrange src/commands directory

### ISSUE THREAD

**Issue by nenes25** [friends-of-presta/fop_console#85]
When i wanted to start working on a new command related with the module hooks,
I feel that the list of class in  the directory is a bit messy 
For examples for files related with hooks :
 
![image](https://user-images.githubusercontent.com/7163132/103228434-1fc28900-4931-11eb-8451-099020f19621.png)

What about defining conventions about file naming and maybe directory creation ?
Should i add an entry in  ADR repository ?

**Comment by SebSept** [comment]
I also think it's messy.

I also feel like there could be an ADR per repository.
Maybe we could add an adr directory in the project... maybe it's useless because of the lack of interactions ... but at least, it's usefull to register decisions. So finaly, I'm ok for an adr.

To simplify things, for the moment, we can also use the dedicated adr repo...

**Comment by jf-viguier** [comment]
Classes should be named like commands, I think that we have  defining conventions for commands first. 
Suggestion : domain:action just like prestashop, or domain-action like doctrine or SF

For this 4 : 
fop:add-hook
fop:unhook-module
fop:hook-module
fop:theme-reset

I suggest :
fop:hook:add
fop:module:hook
fop:module:unhook
fop:theme:reset

WDYT ?

**Comment by nenes25** [comment]
I agree with your suggestion :+1:

So the class name should be the command camelCased ?

fop:hook:add => HookAdd.php
fop:module:hook => ModuleHook.php
fop:module:unhook => ModuleUnHook.php
fop:theme:reset => ThemeReset.php

Or for each domain with several commands should we create a directory

fop:hook:add => Hook/Add.php
fop:module:hook => Module/Hook.php
fop:module:unhook => Module/UnHook.php
fop:theme:reset => Theme/Reset.php

**Comment by SebSept** [comment]
- Domain:action schema looks good for me. @jf-viguier 
- Classname = command camel cased looks good too.

Does it implies a lot of command renaming ?

**Comment by SebSept** [comment]
We also have to take care of the service declaration in services.yml file.

**Comment by SebSept** [comment]
So finally : 
- command name : domain:action (just like prestashop)
- class name : camel cased command name : DomainAction (so filename is DomainAction.php)
- service name : fop.console.domain:action

Are we ok with this ? @nenes25  @jf-viguier

**Comment by jf-viguier** [comment]
It's ok for me, thanks

**Comment by SebSept** [comment]
- To confirm, this should be conform : https://github.com/friends-of-presta/fop_console/pull/89/files
- this should be written somewhere ... but where ? an idea ? (adr, simple file in this repo ?, phpstan custom rule ?)

**Comment by nenes25** [comment]
Hello,
Why not already improve the example command in Reamde file first ?
If possible a phpstan custom rule will be great but i don't know how to do this :/

**Comment by jf-viguier** [comment]
I agree : we can start by adding this convention in the readme. No need pour phpstan, we'll check in human review

**Comment by SebSept** [comment]
ok, so let's put it in the README.md
We require this for the new commands. Then we'll fix the existing commands later.

**Comment by SebSept** [comment]
I'll try to implement a phpstan rule to ensure this. later.

**Comment by Kaudaj** [comment]
Hey! Got some questions to finish my PR:

- Should we keep the ".command" suffix at the end of the services names? 
- What to do about the commands without domain, like Export? Should we create an arbitrary folder, so here it will be Export/Export, or maybe Export/ExportXML?
- Which name should we choose for the list commands like ListEmployees? It should become Employee/List but I can't name it like this as List is a keyword. GetList? GetAll?

**Comment by SebSept** [comment]
> Should we keep the ".command" suffix at the end of the services names?
I think we should.
It's useful when listing services (nowhere else I guess). ( `./bin/console debug:container command` , `./bin/console debug:container fop`)

> What to do about the commands without domain, like Export? Should we create an arbitrary folder, so here it will be Export/Export, or maybe Export/ExportXML?
Imo we should have all commands in a subfolder, but not a big deal. Not sure about the names proposed 🤔 

> Which name should we choose for the list commands like ListEmployees? It should become Employee/List but I can't name it like this as List is a keyword. GetList? GetAll?
imo the className should repeat namespace (folder), just like the command name.
`EmployeList`

We can try with some examples, using : 
- path
- classname
- command name
- service name

From one of them, all the others can be guessed and programmatically generated.

**Comment by Kaudaj** [comment]
Thanks for your answer.

I thought Domain had to be excluded from class name, my bad. Fixed it.
I chose EmployeeList for the class name, it's more logical to me if we follow "DomainAction" convention.

I published the pull request so we can discuss about it more concretely. Feel free to suggest changes there!
https://github.com/friends-of-presta/fop_console/pull/165

**Comment by SebSept** [comment]
👍🏼 Maybe you could code a kind of transformer tool to map from command name to service name, etc.
With this we could enforce a phpstan custom rule ...
I can alse code it, it could be fun ☺️

**Comment by Kaudaj** [comment]
Ok why not!
Never done this before, do you have any idea how I could code it in a nutshell?

**Comment by SebSept** [comment]
My idea is just to check if the correct values are used.
So, for checking,  the small code should generate the names.
A standalone class or just a set of functions could do the job (without PrestaShop dependencies)

**Comment by SebSept** [comment]
fixed #165
