### ISSUE TITLE
Improve issues for asking new command

### ISSUE THREAD

**Issue by nenes25** [friends-of-presta/fop_console#87]
Hello,

Thanks to github template we are able to categorize issues and to provide templates.
This way we can enforce that the issue is comprehensible and clear.

Let me show an example of what's i have done in another project.

When you want to create an issue you can choose your type :
![image](https://user-images.githubusercontent.com/7163132/103367726-26363980-4ac6-11eb-9ff9-29fd1d65d7ee.png)

Then after the user have a pre-filled template 

![image](https://user-images.githubusercontent.com/7163132/103367796-42d27180-4ac6-11eb-8346-ade68a96d838.png)

This way the description is then clear of what need to be done
![image](https://user-images.githubusercontent.com/7163132/103367845-5e3d7c80-4ac6-11eb-977b-fa67e1cb6765.png)

(the same way is used in prestashop  project )

I can make a pull request to improve this if needed
WDYT ?

**Comment by SebSept** [comment]
This could be nice.
👍🏼
